# Generated by Django 3.2.13 on 2022-10-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='otwo',
            field=models.IntegerField(verbose_name=[(2, '심폐지구력')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='part',
            field=models.IntegerField(verbose_name=[(12, '복근')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
